services:  
  essential-nginx-noauth:
    platform: linux/amd64
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-noauth.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - essential-viewer
      - essential-api
      - essential-admin

  essential-viewer:
    platform: linux/amd64
    build: 
      context: viewer
    volumes:
      - ./EssentialAM/essential_viewer:/usr/local/tomcat/webapps/essential_viewer
    ports:
      - 8080:8080
    env_file:
      - ./env_file.env
  
  essential-api:
    build:
      context: https://github.com/terryvel/essential-open-api.git#main
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - ./EssentialAM/Repository:/app/resources/essential
    ports:
      - "5100:5100"
    environment:
      FLASK_APP: wsgi.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: "5100"
      FLASK_DEBUG: "1"
      PPRJ_FILE: "/app/resources/essential/essential_baseline_6_21_0.pprj"
      JARS_DIR: "/app/jars"
      PPRJ_DIR: "/app/resources/essential"
    command: flask run
  
  essential-admin:
    build:
      context: https://github.com/terryvel/essential-open-admin.git#main
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8081:80"
    environment:
      - API_ORIGIN=${API_ORIGIN:-http://localhost:5100}
      - VIEWER_URL=${VIEWER_URL:-http://essential-viewer:8080/essential_viewer}
      - VIEWER_USER=${VIEWER_USER:-publisher}
    env_file:
      - ./env_file.env

