services:  
  viewer:
    image: viewer
    platform: linux/amd64
    hostname: essential-viewer
    build: 
      context: viewer
    volumes:
      - ./EssentialAM/essential_viewer:/usr/local/tomcat/webapps/essential_viewer
    ports:
      - 8080:8080
    env_file:
      - ./env_file.env
  
  api:
    build:
      context: https://github.com/terryvel/essential-open-api.git#main
      dockerfile: Dockerfile
    container_name: essential-api
    volumes:
      - ./EssentialAM/Repository:/app/resources/essential
    ports:
      - "5100:5100"
    environment:
      FLASK_APP: wsgi.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: "5100"
      FLASK_DEBUG: "1"
      PPRJ_FILE: "/app/resources/essential/essential_baseline_6_21_0.pprj"
      JARS_DIR: "/app/jars"
      PPRJ_DIR: "/app/resources/essential"
    command: flask run --debug
      
  # protege:
  #   image: protege
  #   platform: linux/amd64
  #   hostname: essential-protege
  #   build: 
  #     context: protege
  #   volumes:
  #     - ./EssentialAM/Repository:/opt/EssentialAM/Repository
  #     - ./EssentialAM/server:/opt/EssentialAM/server
  #   ports:
  #     - 2222:2222
  #     - 5200:5200
  #     - 5100:5100

  # db:
  #   image: mysql:9.0
  #   hostname: essential-db
  #   env_file:
  #     - ./env_file.env
  #   volumes:
  #     - ./data:/var/lib/mysql
  #     - ./initdb:/docker-entrypoint-initdb.d/
  #   ports:
  #     - "3306:3306"

